# Generated by Django 5.2.15 on 2026-07-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_alter_booking_options_alter_session_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='external_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='external_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='session',
            name='external_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='session',
            name='meeting_url',
            field=models.URLField(blank=True),
        ),
    ]
