# Generated by Django 5.2.15 on 2026-07-03 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_specialavailability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('focus', models.CharField(max_length=150)),
                ('topic', models.CharField(max_length=150)),
                ('default_capacity', models.PositiveIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_offerings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
                'db_table': 'scheduling_classes',
                'ordering': ['subject', 'level', 'focus', 'topic'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='class_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='scheduling.classoffering'),
        ),
        migrations.AddConstraint(
            model_name='classoffering',
            constraint=models.UniqueConstraint(fields=('teacher', 'subject', 'level', 'focus', 'topic'), name='unique_class_offering_per_teacher'),
        ),
    ]
