# Generated by Django 5.2.15 on 2026-07-03 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_classoffering_session_class_offering_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'key'), name='unique_permission_per_teacher')],
            },
        ),
    ]
