# Generated by Django 5.2.15 on 2026-07-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_studioglossary'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioLLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('ollama', 'Ollama (local)'), ('openai_compatible', 'OpenAI-compatible API')], default='openai', max_length=30)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('base_url', models.URLField(blank=True, help_text='Optional. Ollama default http://127.0.0.1:11434; custom for OpenAI-compatible hosts.')),
                ('model_name', models.CharField(default='gpt-4o-mini', max_length=120)),
                ('is_enabled', models.BooleanField(default=False)),
                ('max_tokens', models.PositiveIntegerField(default=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'studio LLM config',
                'verbose_name_plural': 'studio LLM config',
            },
        ),
    ]
