# Generated by Django 5.2.15 on 2026-07-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0021_studiobranding'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboarding_dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10),
        ),
    ]
