# Generated by Django 5.2.15 on 2026-07-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0023_googlecredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, help_text='Calendar event backing the Meet link — used to sync updates/cancellations.', max_length=200),
        ),
    ]
