# Generated by Django 5.2.15 on 2026-07-06 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0024_session_google_calendar_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focuses', to='scheduling.cataloglevel')),
            ],
            options={
                'verbose_name_plural': 'catalog focuses',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='cataloglevel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='scheduling.catalogsubject'),
        ),
        migrations.CreateModel(
            name='CatalogTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='scheduling.catalogfocus')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.AddConstraint(
            model_name='catalogfocus',
            constraint=models.UniqueConstraint(fields=('level', 'name'), name='unique_catalog_focus_per_level'),
        ),
        migrations.AddConstraint(
            model_name='cataloglevel',
            constraint=models.UniqueConstraint(fields=('subject', 'name'), name='unique_catalog_level_per_subject'),
        ),
        migrations.AddConstraint(
            model_name='catalogtopic',
            constraint=models.UniqueConstraint(fields=('focus', 'title'), name='unique_catalog_topic_per_focus'),
        ),
    ]
