# Generated by Django 5.2.15 on 2026-08-26 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0028_staffalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('mock', 'Mock'), ('stripe', 'Stripe'), ('staff', 'Recorded by staff')], default='mock', max_length=20),
        ),
        migrations.CreateModel(
            name='StaffActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_created', 'User created'), ('password_reset', 'Password reset'), ('membership_granted', 'Membership granted'), ('membership_updated', 'Membership updated'), ('tickets_adjusted', 'Tickets adjusted'), ('booking_cancelled', 'Booking cancelled')], db_index=True, max_length=40)),
                ('summary', models.CharField(max_length=300)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, help_text='Optional reason staff typed when making the change.', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
