# Generated by Django 5.2.15 on 2026-09-18 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0030_teacher_student_curriculum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='for_user',
            field=models.ForeignKey(blank=True, help_text='Set on a private plan built for one student.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_membership_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Public plans appear in the student store. Private plans are staff-granted only.'),
        ),
    ]
