# Generated by Django 5.2.15 on 2026-09-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0031_membershipplan_for_user_membershipplan_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculummodule',
            name='cefr_level',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='curriculummodule',
            name='skill_keys',
            field=models.JSONField(blank=True, default=list, help_text='ScoreDimension keys this module trains, e.g. ["grammar", "writing"].'),
        ),
        migrations.AddField(
            model_name='curriculumtrack',
            name='cefr_band',
            field=models.CharField(blank=True, help_text='Set when the whole track sits at one CEFR level.', max_length=2),
        ),
        migrations.AddField(
            model_name='curriculumtrack',
            name='framework',
            field=models.CharField(choices=[('custom', 'Custom'), ('cefr', 'CEFR')], default='custom', max_length=20),
        ),
        migrations.AddField(
            model_name='curriculumtrack',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studiollmconfig',
            name='adaptive_curriculum_enabled',
            field=models.BooleanField(default=False, help_text='Let the AI read reports and suggest curriculum steps. Teachers still approve each one.'),
        ),
    ]
