# Generated by Django 5.2.15 on 2026-09-23 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0008_sessionhistoryprivacy'),
        ('scheduling', '0032_curriculum_cefr_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('next_module', 'Move to next module'), ('supplementary', 'Supplementary material'), ('review', 'Review a module')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('source', models.CharField(choices=[('rules', 'Rules'), ('llm', 'AI')], default='rules', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('rationale', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_suggestions', to='progress.sessionfeedback')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_suggestions_resolved', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_suggestions', to='scheduling.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_suggestions', to=settings.AUTH_USER_MODEL)),
                ('target_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='scheduling.curriculummodule')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_suggestions_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentSupplementaryMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplementary_materials_created', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplementary_materials', to='scheduling.curriculummodule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_materials', to=settings.AUTH_USER_MODEL)),
                ('suggestion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material', to='scheduling.curriculumsuggestion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
