# Generated by Django 5.2.15 on 2026-09-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0033_curriculum_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='student_can_renew',
            field=models.BooleanField(default=False, help_text='Private plans only: the owning student may buy or renew it from their membership page.'),
        ),
    ]
