# Generated by Django 5.2.15 on 2026-09-24 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0034_membershipplan_student_can_renew'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'branches',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='accepts_walk_ins',
            field=models.BooleanField(default=False, help_text='Students may still book while the class is in progress.'),
        ),
        migrations.AddField(
            model_name='session',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Set for in-branch classes placed inside branch hours. Blank means a private session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='scheduling.branch'),
        ),
        migrations.CreateModel(
            name='BranchHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='scheduling.branch')),
            ],
            options={
                'verbose_name_plural': 'branch hours',
                'ordering': ['weekday', 'start_time'],
            },
        ),
    ]
