# Generated by Django 5.2.15 on 2026-09-24 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_catalog_to_tracks(apps, schema_editor):
    from scheduling.services.curriculum_link import link_catalog_to_tracks as link

    link(apps)


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0035_branch_open_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classoffering',
            name='track',
            field=models.ForeignKey(blank=True, help_text='The curriculum this teacher teaches. Subject, level, and focus are cached from it.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='scheduling.curriculumtrack'),
        ),
        migrations.AddField(
            model_name='classrequest',
            name='curriculum_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_requests', to='scheduling.curriculummodule'),
        ),
        migrations.AddField(
            model_name='session',
            name='curriculum_module',
            field=models.ForeignKey(blank=True, help_text='The lesson this session teaches, from the class track.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='scheduling.curriculummodule'),
        ),
        migrations.AddConstraint(
            model_name='classoffering',
            constraint=models.UniqueConstraint(condition=models.Q(('track__isnull', False)), fields=('teacher', 'track'), name='unique_class_offering_per_teacher_track'),
        ),
        migrations.RunPython(link_catalog_to_tracks, migrations.RunPython.noop),
    ]
