# Generated by Django 5.2.15 on 2026-09-30 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0036_curriculum_track_on_classes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioCheckInConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_opens_hours_before', models.PositiveIntegerField(default=24, help_text='Students and the teacher may check in this many hours before the lesson starts.')),
                ('reminder_hours_before', models.PositiveIntegerField(default=3, help_text='If someone has not checked in, send a reminder this many hours before start.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'studio check-in config',
                'verbose_name_plural': 'studio check-in config',
            },
        ),
        migrations.CreateModel(
            name='SessionCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='scheduling.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_check_ins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'user'), name='unique_checkin_per_user_session')],
            },
        ),
    ]
