# Generated by Django 5.2.15 on 2026-07-03 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_sessionfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('label', models.CharField(max_length=100)),
                ('feedback_field', models.CharField(max_length=50)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_dimensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'key'), name='unique_score_dimension_per_teacher')],
            },
        ),
    ]
