# Generated by Django 5.2.15 on 2026-07-03 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import progress.models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_scoredimension_min_max'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('file', 'File exchange'), ('journal', 'Journal prompt')], default='file', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('prompt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='File-exchange threads stop accepting uploads after this time.', null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_received', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_assigned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to=progress.models.homework_upload_path)),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('attachment_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='progress.homeworkassignment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
