# Generated by Django 5.2.15 on 2026-07-06 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_homework_session'),
        ('scheduling', '0021_studiobranding'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionHistoryPrivacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_by_student', models.BooleanField(default=False)),
                ('hidden_by_teacher', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_privacy', to='scheduling.session')),
            ],
            options={
                'verbose_name_plural': 'session history privacy',
            },
        ),
    ]
