from django.contrib import admin

from .models import (
    AvailabilityBlock,
    BlogPost,
    Booking,
    CatalogFocus,
    CatalogLevel,
    CatalogSubject,
    CatalogTopic,
    ClassOffering,
    ClassRequest,
    ClassTopic,
    ClassType,
    CurriculumItem,
    DemoItem,
    Membership,
    MembershipPlan,
    Message,
    Payment,
    Profile,
    Session,
    SpecialAvailability,
    StaffAlert,
    StaffAlertRead,
    StudioBranding,
    StudioGlossary,
    StudioLLMConfig,
    TeacherPermission,
)

admin.site.register(DemoItem)
admin.site.register(Profile)
admin.site.register(ClassType)
admin.site.register(ClassOffering)
admin.site.register(ClassTopic)
admin.site.register(CatalogSubject)
admin.site.register(CatalogLevel)
admin.site.register(CatalogFocus)
admin.site.register(CatalogTopic)
admin.site.register(TeacherPermission)
admin.site.register(StudioGlossary)
admin.site.register(StudioBranding)
admin.site.register(StudioLLMConfig)
admin.site.register(AvailabilityBlock)
admin.site.register(SpecialAvailability)
admin.site.register(Session)
admin.site.register(Booking)
admin.site.register(MembershipPlan)
admin.site.register(Membership)
admin.site.register(Payment)
admin.site.register(BlogPost)
admin.site.register(ClassRequest)
admin.site.register(Message)
admin.site.register(CurriculumItem)
admin.site.register(StaffAlert)
admin.site.register(StaffAlertRead)
