from django.urls import path

from progress.api.history import TeacherSessionHistoryPrivacyView, TeacherStudentHistoryView
from scheduling.api import blog_views, branding_views, class_catalog_views, class_request_views, google_views, staff_views, views
from scheduling.api.auth_views import (
    StudentRegisterView,
    ThrottledTokenObtainPairView,
    ThrottledTokenRefreshView,
)
from scheduling.api.glossary_views import GlossaryListView, StaffGlossaryView
from scheduling.api.llm_views import (
    StaffLLMConfigView,
    StaffLLMTestView,
    TeacherAIStatusView,
    TeacherAISuggestFeedbackView,
)

urlpatterns = [
    path('auth/token/', ThrottledTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('auth/token/refresh/', ThrottledTokenRefreshView.as_view(), name='token_refresh'),
    path('auth/register/', StudentRegisterView.as_view(), name='student_register'),
    path('me/', views.MeView.as_view(), name='api_me'),
    path('me/onboarding/', views.MeOnboardingView.as_view(), name='api_me_onboarding'),
    path('markdown/preview/', views.MarkdownPreviewView.as_view(), name='api_markdown_preview'),
    path('glossary/', GlossaryListView.as_view(), name='api_glossary'),
    path('class-catalog/', class_catalog_views.ClassCatalogListView.as_view(), name='api_class_catalog'),
    path('branding/', branding_views.PublicBrandingView.as_view(), name='api_branding'),
    path('upload-limits/', blog_views.UploadLimitsView.as_view(), name='api_upload_limits'),
    path('blog/', blog_views.BlogPostListView.as_view(), name='api_blog_list'),
    path('blog/manage/', blog_views.BlogPostManageListCreateView.as_view(), name='api_blog_manage'),
    path('blog/<int:pk>/', blog_views.BlogPostDetailView.as_view(), name='api_blog_detail'),
    path('me/password/', views.PasswordChangeView.as_view(), name='api_password_change'),
    path('sessions/open/', views.OpenSessionListView.as_view(), name='api_open_sessions'),
    path('bookings/', views.MyBookingListView.as_view(), name='api_my_bookings'),
    path('bookings/create/', views.BookingCreateView.as_view(), name='api_booking_create'),
    path('bookings/<int:booking_id>/cancel/', views.BookingCancelView.as_view(), name='api_booking_cancel'),
    path('class-requests/teachers/', class_request_views.ClassRequestTeacherListView.as_view(), name='api_class_request_teachers'),
    path('class-requests/open-classes/', class_request_views.ClassRequestOpenClassesView.as_view(), name='api_class_request_open_classes'),
    path('class-requests/classes/', class_request_views.ClassRequestTeacherClassesView.as_view(), name='api_class_request_classes'),
    path('class-requests/availability/', class_request_views.ClassRequestAvailabilityView.as_view(), name='api_class_request_availability'),
    path('class-requests/open-availability/', class_request_views.ClassRequestOpenAvailabilityView.as_view(), name='api_class_request_open_availability'),
    path('class-requests/', class_request_views.StudentClassRequestListCreateView.as_view(), name='api_class_requests'),
    path('class-requests/<int:pk>/', class_request_views.StudentClassRequestDetailView.as_view(), name='api_class_request_detail'),
    path('teacher/class-requests/', class_request_views.TeacherClassRequestListView.as_view(), name='api_teacher_class_requests'),
    path('teacher/class-requests/<int:pk>/', class_request_views.TeacherClassRequestDetailView.as_view(), name='api_teacher_class_request_detail'),
    path('teacher/class-requests/<int:pk>/approve/', class_request_views.TeacherClassRequestApproveView.as_view(), name='api_teacher_class_request_approve'),
    path('teacher/class-requests/<int:pk>/deny/', class_request_views.TeacherClassRequestDenyView.as_view(), name='api_teacher_class_request_deny'),
    path('teacher/class-requests/<int:pk>/delete/', class_request_views.TeacherClassRequestDeleteView.as_view(), name='api_teacher_class_request_delete'),
    path('teacher/sessions/', views.TeacherSessionListCreateView.as_view(), name='api_teacher_sessions'),
    path(
        'teacher/sessions/availability-check/',
        views.TeacherSessionAvailabilityCheckView.as_view(),
        name='api_teacher_session_availability_check',
    ),
    path(
        'teacher/sessions/<int:session_id>/',
        views.TeacherSessionDetailView.as_view(),
        name='api_teacher_session_detail',
    ),
    path(
        'teacher/sessions/<int:session_id>/students/',
        views.TeacherSessionStudentsView.as_view(),
        name='api_teacher_session_students',
    ),
    path('teacher/students/', views.TeacherStudentListView.as_view(), name='api_teacher_students'),
    path(
        'teacher/students/<int:student_id>/history/',
        TeacherStudentHistoryView.as_view(),
        name='api_teacher_student_history',
    ),
    path(
        'teacher/sessions/<int:session_id>/history-privacy/',
        TeacherSessionHistoryPrivacyView.as_view(),
        name='api_teacher_session_history_privacy',
    ),
    path('teacher/availability/', views.TeacherAvailabilityListCreateView.as_view(), name='api_teacher_availability'),
    path(
        'teacher/availability/<int:pk>/',
        views.TeacherAvailabilityUpdateDeleteView.as_view(),
        name='api_teacher_availability_detail',
    ),
    path(
        'teacher/special-availability/',
        views.TeacherSpecialAvailabilityListCreateView.as_view(),
        name='api_teacher_special_availability',
    ),
    path(
        'teacher/special-availability/<int:pk>/',
        views.TeacherSpecialAvailabilityUpdateDeleteView.as_view(),
        name='api_teacher_special_availability_detail',
    ),
    path(
        'teacher/scheduling-slots/',
        views.TeacherSchedulingSlotsView.as_view(),
        name='api_teacher_scheduling_slots',
    ),
    path('teacher/classes/', views.TeacherClassOfferingListCreateView.as_view(), name='api_teacher_classes'),
    path(
        'teacher/classes/<int:pk>/',
        views.TeacherClassOfferingDetailView.as_view(),
        name='api_teacher_class_detail',
    ),
    path('teacher/permissions/', views.TeacherPermissionsView.as_view(), name='api_teacher_permissions'),
    path('messages/', views.InboxListView.as_view(), name='api_inbox'),
    path('curriculum/', views.CurriculumListView.as_view(), name='api_curriculum'),
    path('membership/', views.MembershipView.as_view(), name='api_membership'),
    path('membership/plans/', views.MembershipPlanCatalogView.as_view(), name='api_membership_plans'),
    path('membership/payment-config/', views.MembershipPaymentConfigView.as_view(), name='api_membership_payment_config'),
    path('membership/checkout/', views.MembershipCheckoutView.as_view(), name='api_membership_checkout'),
    path(
        'membership/payments/<int:payment_id>/',
        views.MembershipPaymentStatusView.as_view(),
        name='api_membership_payment_status',
    ),
    path('payments/stripe/webhook/', views.StripeWebhookView.as_view(), name='api_stripe_webhook'),
    path('integrations/google/connect/', google_views.GoogleConnectView.as_view(), name='api_google_connect'),
    path('integrations/google/status/', google_views.GoogleStatusView.as_view(), name='api_google_status'),
    path('integrations/google/disconnect/', google_views.GoogleDisconnectView.as_view(), name='api_google_disconnect'),
    path('staff/glossary/', StaffGlossaryView.as_view(), name='api_staff_glossary'),
    path('staff/branding/', branding_views.StaffBrandingView.as_view(), name='api_staff_branding'),
    path('staff/llm/', StaffLLMConfigView.as_view(), name='api_staff_llm'),
    path('staff/llm/test/', StaffLLMTestView.as_view(), name='api_staff_llm_test'),
    path('teacher/ai/status/', TeacherAIStatusView.as_view(), name='api_teacher_ai_status'),
    path('teacher/ai/suggest-feedback/', TeacherAISuggestFeedbackView.as_view(), name='api_teacher_ai_suggest'),
    path('staff/teachers/', staff_views.StaffTeacherListView.as_view(), name='api_staff_teachers'),
    path('staff/students/', staff_views.StaffStudentListView.as_view(), name='api_staff_students'),
    path('staff/students/<int:student_id>/', staff_views.StaffStudentDetailView.as_view(), name='api_staff_student_detail'),
    path('staff/schedule/', staff_views.StaffOverallScheduleView.as_view(), name='api_staff_schedule'),
    path(
        'staff/teachers/<int:teacher_id>/',
        staff_views.StaffTeacherDetailView.as_view(),
        name='api_staff_teacher_detail',
    ),
    path(
        'staff/teachers/<int:teacher_id>/sessions/',
        staff_views.StaffTeacherSessionListCreateView.as_view(),
        name='api_staff_teacher_sessions',
    ),
    path(
        'staff/teachers/<int:teacher_id>/sessions/availability-check/',
        staff_views.StaffTeacherSessionAvailabilityCheckView.as_view(),
        name='api_staff_teacher_session_availability_check',
    ),
    path(
        'staff/teachers/<int:teacher_id>/sessions/<int:session_id>/',
        staff_views.StaffTeacherSessionDetailView.as_view(),
        name='api_staff_teacher_session_detail',
    ),
    path(
        'staff/teachers/<int:teacher_id>/sessions/<int:session_id>/students/',
        staff_views.StaffTeacherSessionStudentsView.as_view(),
        name='api_staff_teacher_session_students',
    ),
    path(
        'staff/teachers/<int:teacher_id>/classes/',
        staff_views.StaffTeacherClassListCreateView.as_view(),
        name='api_staff_teacher_classes',
    ),
    path(
        'staff/teachers/<int:teacher_id>/classes/<int:pk>/',
        staff_views.StaffTeacherClassDetailView.as_view(),
        name='api_staff_teacher_class_detail',
    ),
    path(
        'staff/teachers/<int:teacher_id>/availability/',
        staff_views.StaffTeacherAvailabilityListCreateView.as_view(),
        name='api_staff_teacher_availability',
    ),
    path(
        'staff/teachers/<int:teacher_id>/availability/<int:pk>/',
        staff_views.StaffTeacherAvailabilityUpdateDeleteView.as_view(),
        name='api_staff_teacher_availability_detail',
    ),
    path(
        'staff/teachers/<int:teacher_id>/special-availability/',
        staff_views.StaffTeacherSpecialAvailabilityListCreateView.as_view(),
        name='api_staff_teacher_special_availability',
    ),
    path(
        'staff/teachers/<int:teacher_id>/special-availability/<int:pk>/',
        staff_views.StaffTeacherSpecialAvailabilityUpdateDeleteView.as_view(),
        name='api_staff_teacher_special_availability_detail',
    ),
    path(
        'staff/teachers/<int:teacher_id>/scheduling-slots/',
        staff_views.StaffTeacherSchedulingSlotsView.as_view(),
        name='api_staff_teacher_scheduling_slots',
    ),
    path(
        'staff/teachers/<int:teacher_id>/students/',
        staff_views.StaffTeacherStudentListView.as_view(),
        name='api_staff_teacher_students',
    ),
    path(
        'staff/teachers/<int:teacher_id>/permissions/',
        staff_views.StaffTeacherPermissionsView.as_view(),
        name='api_staff_teacher_permissions',
    ),
    path(
        'staff/teachers/<int:teacher_id>/class-requests/',
        class_request_views.TeacherClassRequestListView.as_view(),
        name='api_staff_teacher_class_requests',
    ),
    path(
        'staff/teachers/<int:teacher_id>/class-requests/<int:pk>/',
        class_request_views.TeacherClassRequestDetailView.as_view(),
        name='api_staff_teacher_class_request_detail',
    ),
    path(
        'staff/teachers/<int:teacher_id>/class-requests/<int:pk>/approve/',
        class_request_views.TeacherClassRequestApproveView.as_view(),
        name='api_staff_teacher_class_request_approve',
    ),
    path(
        'staff/teachers/<int:teacher_id>/class-requests/<int:pk>/deny/',
        class_request_views.TeacherClassRequestDenyView.as_view(),
        name='api_staff_teacher_class_request_deny',
    ),
    path(
        'staff/teachers/<int:teacher_id>/class-requests/<int:pk>/delete/',
        class_request_views.TeacherClassRequestDeleteView.as_view(),
        name='api_staff_teacher_class_request_delete',
    ),
    path('staff/classes/', staff_views.StaffCreateClassView.as_view(), name='api_staff_create_class'),
    path('staff/class-catalog/', class_catalog_views.StaffClassCatalogView.as_view(), name='api_staff_class_catalog'),
    path(
        'staff/class-catalog/focuses/<int:focus_id>/topics/bulk/',
        class_catalog_views.StaffClassCatalogBulkTopicsView.as_view(),
        name='api_staff_class_catalog_bulk_topics',
    ),
    path('staff/class-offerings/', staff_views.StaffClassOfferingListView.as_view(), name='api_staff_class_offerings'),
    path('staff/membership-plans/', staff_views.StaffMembershipPlanListCreateView.as_view(), name='api_staff_membership_plans'),
    path(
        'staff/membership-plans/<int:pk>/',
        staff_views.StaffMembershipPlanDetailView.as_view(),
        name='api_staff_membership_plan_detail',
    ),
    path('staff/reports/', staff_views.StaffReportsView.as_view(), name='api_staff_reports'),
]
